services:
  web:
    build: .
    image: salonhub-web
    container_name: salonhub_backend_app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      # Django
      SECRET_KEY: your-secret-key
      DEBUG: "False"

      # Database
      DB_NAME: salon_db
      DB_USER: salon_user
      DB_PASSWORD: StrongPassword123
      DB_HOST: db
      DB_PORT: 5432

      # Celery / Redis
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: salon_db
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: StrongPassword123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_server
    # ⚠️ No ports needed in production

  celery_worker:
    build: .
    image: salonhub-web
    container_name: celery_worker
    command: celery -A backend worker -l info
    depends_on:
      - db
      - redis
    environment:
      # Database (MANDATORY)
      DB_NAME: salon_db
      DB_USER: salon_user
      DB_PASSWORD: StrongPassword123
      DB_HOST: db
      DB_PORT: 5432

      # Celery / Redis
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      # Django
      SECRET_KEY: your-secret-key
      DEBUG: "False"

  celery_beat:
    build: .
    image: salonhub-web
    container_name: celery_beat
    command: celery -A backend beat -l info
    depends_on:
      - db
      - redis
    environment:
      # Database (MANDATORY)
      DB_NAME: salon_db
      DB_USER: salon_user
      DB_PASSWORD: StrongPassword123
      DB_HOST: db
      DB_PORT: 5432

      # Celery / Redis
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      # Django
      SECRET_KEY: your-secret-key
      DEBUG: "False"

volumes:
  pgdata:
